apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: tomcat-demo
  name: tomcat-balancer
  namespace: tomcat-demo
spec:
  ports:
  - nodePort: 30666
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: tomcat-demo
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
